<?php


namespace source\libs;

use source\LsYii;
use source\libs\Common;

class Language
{
    public static function aLangs()
    {
        return [
            'sq'=>'阿尔巴尼亚语【shqiptar】',
            'ar'=>'阿拉伯语【العربية】',
            'az'=>'阿塞拜疆语【Azərbaycan】',
            'ga'=>'爱尔兰语【teanga Gaeilge】',
            'et'=>'爱沙尼亚语【eesti】',
            'eu'=>'巴斯克语【Euskal】',
            'be'=>'白俄罗斯语【беларускі】',
            'bg'=>'保加利亚语【български】',
            'is'=>'冰岛语【íslenska】',
            'pl'=>'波兰语【Polskie】',
            'bs'=>'波斯尼亚语【bosanski】',
            'fa'=>'波斯语【فارسی】',
            'af'=>'布尔语(南非荷兰语)【Boole taal (Afrikaans)】',
            'da'=>'丹麦语【danske】',
            'de'=>'德语【Deutsch】',
            'ru'=>'俄语【русский】',
            'fr'=>'法语【français】',
            'tl'=>'菲律宾语【Pilipino】',
            'fi'=>'芬兰语【suomi】',
            'km'=>'高棉语【ជាភាសាខ្មែរ】',
            'ka'=>'格鲁吉亚语【ქართული】',
            'gu'=>'古吉拉特语【ગુજરાતી】',
            'kk'=>'哈萨克语【Қазақ тілі】',
            'ht'=>'海地克里奥尔语【Kreyòl ayisyen】',
            'ko'=>'韩语【한국의】',
            'ha'=>'豪萨语【Hausa】',
            'nl'=>'荷兰语【nederlandse】',
            'gl'=>'加利西亚语【Galego】',
            'ca'=>'加泰罗尼亚语【Català】',
            'cs'=>'捷克语【čeština】',
            'kn'=>'卡纳达语【ಕನ್ನಡ】',
            'hr'=>'克罗地亚语【hrvatska】',
            'la'=>'拉丁语【Latine】',
            'lv'=>'拉脱维亚语【Latvijā】',
            'lo'=>'老挝语【ພາສາລາວ】',
            'lt'=>'立陶宛语【Lietuvos】',
            'ro'=>'罗马尼亚语【român】',
            'mg'=>'马尔加什语【Malagasy】',
            'mt'=>'马耳他语【Malti】',
            'mr'=>'马拉地语【मराठी】',
            'ml'=>'马拉雅拉姆语【മലയാളം】',
            'ms'=>'马来语【Melayu】',
            'mk'=>'马其顿语【македонски】',
            'mi'=>'毛利语【Maori】',
            'mn'=>'蒙古语【Монгол】',
            'bn'=>'孟加拉语【বাংলা ভাষা】',
            'my'=>'缅甸语【မြန်မာ】',
            'hmn'=>'苗语【Hmong】',
            'zu'=>'南非祖鲁语【South Africa Zulu】',
            'ne'=>'尼泊尔语【नेपाली】',
            'no'=>'挪威语【norsk språk】',
            'pa'=>'旁遮普语【ਪੰਜਾਬੀ ਦੇ】',
            'pt'=>'葡萄牙语【português】',
            'ny'=>'齐切瓦语【Chichewa】',
            'ja'=>'日语【日本人】',
            'sv'=>'瑞典语【svenska】',
            'sr'=>'塞尔维亚语【Српски језик】',
            'st'=>'塞索托语【Sesotho】',
            'si'=>'僧伽罗语【සිංහල】',
            'eo'=>'世界语【Esperanton】',
            'sk'=>'斯洛伐克语【slovenský jazyk】',
            'sl'=>'斯洛文尼亚语【slovenščina】',
            'sw'=>'斯瓦希里语【lugha ya Kiswahili】',
            'ceb'=>'宿务语【Cebuano】',
            'so'=>'索马里语【Soomaali】',
            'tg'=>'塔吉克语【ба забони тоҷикӣ】',
            'te'=>'泰卢固语【తెలుగు】',
            'ta'=>'泰米尔语【தமிழ் மொழி】',
            'th'=>'泰语【ไทย】',
            'tr'=>'土耳其语【Türk】',
            'cy'=>'威尔士语【Cymraeg】',
            'ur'=>'乌尔都语【اردو زبان】',
            'uk'=>'乌克兰语【Український】',
            'uz'=>'乌兹别克语【O\'zbekiston】',
            'iw'=>'希伯来语【עברית】',
            'el'=>'希腊语【Ελληνική】',
            'es'=>'西班牙语【español】',
            'hu'=>'匈牙利语【magyar】',
            'hy'=>'亚美尼亚语【հայերեն】',
            'ig'=>'伊博语【Igbo】',
            'it'=>'意大利语【lingua italiana】',
            'yi'=>'意第绪语【ייִדיש】',
            'hi'=>'印地语【हिन्दी】',
            'su'=>'印尼巽他语【Indonesia Sunda】',
            'id'=>'印尼语【indonesia】',
            'jw'=>'印尼爪哇语【Jawa Indonesia】',
            'en'=>'英语【English】',
            'yo'=>'约鲁巴语【yorùbá】',
            'vi'=>'越南语【tiếng việt】',
            'zh-TW'=>'中文(繁体)【中文(繁體)】',
            'zh-CN'=>'中文(简体)【中文(简体)】',
        ];
    }
}
